In [1]:
from bs4 import BeautifulSoup as bs
from splinter import Browser
import pandas as pd
import os
import time
import requests
import warnings
warnings.filterwarnings('ignore')

In [2]:
# def init_browser():
#     executable_path = {"executable_path": "/usr/local/bin/chromedriver"}
#     return Browser("chrome", **executable_path, headless=False)

In [3]:
# url_nfl = "https://www.pro-football-reference.com/years/2006/draft.htm"

# nfl_player_table = pd.read_html(url_nfl, skiprows=0)[0]

In [4]:
# nfl_player_table

In [5]:
# for col in nfl_player_table.columns:
#     print(col)

In [6]:
# nfl_player_table.columns = ["Round", "Pick", "Team", "Player", "Position", "Age", "Until", "AP1", "PB", "YearsStarter", "CareerAverage", "DraftAverage", "Games", "PassComp", "PassAtt", "PassYards", "PassTDs", "Int", "RushAtt", "RushYards", "RushTDs", "Rec", "RecYards", "RecTDs", "TackleSolo", "DefInt", "Sacks", "College", "CollegeLink"]

In [7]:
# nfl_player_table

In [8]:
df = pd.read_excel('Resources/Draft_Players.xlsx')
df

,Round,Pick,Team,Player,First,Last,Position,Age,Until,AP1,...,RushAtt,RushYards,RushTDs,Rec,RecYards,RecTDs,TackleSolo,DefensiveInt,Sacks,College
0,1,1,HOU,Mario Williams,Mario,Williams,DE,21.0,2016.0,1,...,0,0,0,0,0,0,317,0,97.5,North Carolina St.
1,1,2,NOR,Reggie Bush,Reggie,Bush,RB,21.0,2016.0,0,...,1286,5490,36,477,3598,18,0,0,0.0,USC
2,1,3,TEN,Vince Young,Vince,Young,QB,23.0,2011.0,0,...,282,1459,12,0,0,0,0,0,0.0,Texas
3,1,4,NYJ,DBrickashaw Ferguson,DBrickashaw,Ferguson,T,22.0,2015.0,0,...,0,0,0,0,0,0,0,0,0.0,Virginia
4,1,5,GNB,AJ Hawk,AJ,Hawk,LB,22.0,2016.0,0,...,0,0,0,0,0,0,645,9,20.0,Ohio St.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,7,251,HOU,David Anderson,David,Anderson,WR,23.0,2011.0,0,...,0,0,0,88,965,4,8,0,0.0,Colorado St.
251,7,252,NOR,Marques Colston,Marques,Colston,WR,23.0,2015.0,0,...,2,7,0,711,9759,72,1,0,0.0,Hofstra
252,7,253,GNB,Dave Tollefson,Dave,Tollefson,DE,24.0,2012.0,0,...,0,0,0,0,0,0,62,0,10.5,NW Missouri St.
253,7,254,SFO,Vickiel Vaughn,Vickiel,Vaughn,DB,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0.0,Arkansas
254,7,255,OAK,Kevin McMahan,Kevin,McMahan,WR,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0.0,Maine

In [9]:
players = df['Player'].tolist()
players

['Mario Williams',
 'Reggie Bush',
 'Vince Young',
 'DBrickashaw Ferguson',
 'AJ Hawk',
 'Vernon Davis',
 'Michael Huff',
 'Donte Whitner',
 'Ernie Sims',
 'Matt Leinart',
 'Jay Cutler',
 'Haloti Ngata',
 'Kamerion Wimbley',
 'Brodrick Bunkley',
 'Tye Hill',
 'Jason Allen',
 'Chad Greenway',
 'Bobby Carpenter',
 'Antonio Cromartie',
 'Tamba Hali',
 'Laurence Maroney',
 'Manny Lawson',
 'Davin Joseph',
 'Johnathan Joseph',
 'Santonio Holmes',
 'John McCargo',
 'DeAngelo Williams',
 'Marcedes Lewis',
 'Nick Mangold',
 'Joseph Addai',
 'Kelly Jennings',
 'Mathias Kiwanuka',
 'DeMeco Ryans',
 'DQwell Jackson',
 'Rocky McIntosh',
 'Chad Jackson',
 'Jimmy Williams',
 'Thomas Howard',
 'Winston Justice',
 'Daniel Bullocks',
 'Deuce Lutui',
 'Danieal Manning',
 'Roman Harper',
 'Sinorice Moss',
 'LenDale White',
 'Joe Klopfenstein',
 'Daryn Colledge',
 'Cedric Griffin',
 'Kellen Clemens',
 'Marcus McNeill',
 'Ryan Cook',
 'Greg Jennings',
 'Anthony Fasano',
 'Bernard Pollard',
 'Andrew Whitworth',
 'Chris Chester',
 'Devin Hester',
 'Richard Marshall',
 'Jeremy Trueblood',
 'Maurice JonesDrew',
 'Tony Scheffler',
 'Tim Jennings',
 'Darryl Tapp',
 'Tarvaris Jackson',
 'Charles Spencer',
 'Eric Winston',
 'Abdul Hodge',
 'Claude Wroten',
 'Paul McQuistan',
 'Ashton Youboty',
 'Chris Gocong',
 'Leonard Pope',
 'Dusty Dvoracek',
 'Brian Calhoun',
 'Jason Spitz',
 'Anthony Schlegel',
 'Jon Alston',
 'Travis Wilson',
 'Jerious Norwood',
 'Clint Ingram',
 'Charlie Whitehurst',
 'Derek Hagan',
 'Anthony Smith',
 'Brandon Williams',
 'Brodie Croyle',
 'David Thomas',
 'David Pittman',
 'James Anderson',
 'Rashad Butler',
 'Maurice Stovall',
 'Frostee Rucker',
 'Jason Hatcher',
 'Dominique Byrd',
 'Freddy Keiaho',
 'Willie Reid',
 'Gerris Wilkinson',
 'Eric Smith',
 'Owen Daniels',
 'Max JeanGilles',
 'Michael Robinson',
 'Darnell Bing',
 'Calvin Lowry',
 'Brad Smith',
 'Cory Rodgers',
 'Ko Simpson',
 'Garrett Mills',
 'Gabe Watson',
 'Jahri Evans',
 'Jason Avant',
 'Leon Williams',
 'Demetrius Williams',
 'Isaac Sowells',
 'Victor Adeyanju',
 'Joe Toledo',
 'Will Blackmon',
 'Stephen Tulloch',
 'Leon Washington',
 'Stephen Gostkowski',
 'Brandon Marshall',
 'Jamar Williams',
 'Nate Salley',
 'Alan Zemaitis',
 'Domata Peko',
 'Barry Cofield',
 'Skyler Green',
 'Elvis Dumervil',
 'Ray Edwards',
 'Rob Sims',
 'Guy Whimper',
 'Domenik Hixon',
 'Willie Colon',
 'PJ Daniels',
 'Orien Harris',
 'Kyle Williams',
 'Rob Ninkovich',
 'Ryan OCallaghan',
 'Terna Nande',
 'Pat Watkins',
 'Quinn Ojinnaka',
 'Parys Haralson',
 'Jonathan Scott',
 'Brandon Johnson',
 'Brad Butler',
 'Marques Hagans',
 'Jerome Harrison',
 'Dawan Landry',
 'Jeremy Bloom',
 'Ingle Martin',
 'Greg Blue',
 'Jason Pociask',
 'Tim Dobbins',
 'DeMario Minter',
 'Anthony Montgomery',
 'Marcus Maxey',
 'Jeff King',
 'Julian Jenkins',
 'AJ Nicholson',
 'Charlie Peprah',
 'Mark Anderson',
 'Brent Hawkins',
 'Chris Kuper',
 'Michael Toudouze',
 'David Kirtman',
 'Omar Jacobs',
 'Tony Moll',
 'Quinn Sypniewski',
 'Charles Davis',
 'Omar Gaither',
 'Jesse Mahelona',
 'Wali Lundy',
 'Mike Hass',
 'Jonathan Orr',
 'Reed Doughty',
 'Josh Lay',
 'Delanie Walker',
 'Kevin Boothe',
 'Jonathan Lewis',
 'Keith Ellison',
 'Dee McCann',
 'Lawrence Vickers',
 'Babatunde Oshinowo',
 'Montavious Stanley',
 'Johnny Jolly',
 'Adam Jennings',
 'Tyrone Culver',
 'Tre Stallings',
 'Jeromey Clary',
 'Kurt Smith',
 'Drew Coleman',
 'Jeff Webb',
 'Jeremy Mincey',
 'Marcus Hudson',
 'Reggie McNeal',
 'Bruce Gradkowski',
 'JD Runnels',
 'Kedric Golston',
 'Melvin Oliver',
 'Greg Eslinger',
 'Charlie Johnson',
 'Tyler Reed',
 'Marvin Philip',
 'TJ Williams',
 'Sam Koch',
 'LaJuan Ramsey',
 'Dan Stevenson',
 'Le Kevin Smith',
 'Antoine Bethea',
 'Derrick Martin',
 'Ethan Kilmer',
 'Zach Strief',
 'Pat McQuistan',
 'Fred Evans',
 'James Wyche',
 'Chris Morris',
 'Cortland Finnegan',
 'Terrance Pennington',
 'Fred Matua',
 'Todd Watkins',
 'Ryan LaCasse',
 'Titus Adams',
 'Tim McGarigle',
 'Justin Hamilton',
 'DJ Shockley',
 'EJ Whitley',
 'Chase Page',
 'Rodrique Wright',
 'Jimmy Martin',
 'Jarrad Page',
 'Willie Andrews',
 'Kili Lefotu',
 'Bennie Brazell',
 'Gerrick McPhearson',
 'Devin Aromashodu',
 'Will Montgomery',
 'Justin Phinisee',
 'Dee Webb',
 'Stanley McClover',
 'TJ Rushing',
 'Ryan Plackemeier',
 'Cedric Humes',
 'Charles Bennett',
 'Mark Setterstrom',
 'Tony Palmer',
 'Tim Massaquoi',
 'Spencer Toone',
 'Quinton Ganther',
 'Anthony Cannon',
 'Aaron Merz',
 'Ben Obomanu',
 'Kevin Simon',
 'David Anderson',
 'Marques Colston',
 'Dave Tollefson',
 'Vickiel Vaughn',
 'Kevin McMahan']

In [10]:
college_stats = pd.DataFrame(columns = ['Player', 'passCmp', 'passAtt', 'passPct', 'passYds', 'passY/A', 'passAY/A', 'passTD', 'passInt', 'passRate', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'recRec', 'recYds', 'recAvg', 'recTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts', 'Punts', 'puntYds', 'puntAvg', 'tackleSolo', 'tackleAst', 'tackleTot', 'tackleLoss', 'Sk', 'defInt', 'defYds', 'defAvg', 'defIntTD', 'defIntPD', 'fumFR', 'fumYds', 'fumTD', 'fumFF'])
college_stats['Player'] = players
# college_stats = college_stats.dropna(axis=1, how='all')
# college_stats = college_stats.set_index(college_stats.Player)
# college_stats = college_stats.rename(columns={'Player': 'Name'})
college_stats

,Player,passCmp,passAtt,passPct,passYds,passY/A,passAY/A,passTD,passInt,passRate,...,Sk,defInt,defYds,defAvg,defIntTD,defIntPD,fumFR,fumYds,fumTD,fumFF
0,Mario Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Reggie Bush,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Vince Young,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DBrickashaw Ferguson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AJ Hawk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,David Anderson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,Marques Colston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,Dave Tollefson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,Vickiel Vaughn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Kevin McMahan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# x = 0

# for _ in df:
#     try:
#         pre_url = "https://www.sports-reference.com/cfb/players/"
#         post_url = "-1.html"
#         first = df.First[x].lower()
#         last = df.Last[x].lower()
#         full_url = f'{pre_url}{first}-{last}{post_url}'
    
#         if df.Position[x] == 'QB':
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'passCmp', 'passAtt', 'passPct', 'passYds', 'passY/A', 'passAY/A', 'passTD', 'passInt', 'passRate']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             df_player = df_player.set_index(df_player.Player)
#             pd.merge(df_player, college_stats)
        
#         elif df.Position[x] == 'RB':
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'recRec', 'recYds', 'recAvg', 'recTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             pd.merge(df_player, college_stats)
            
#         elif df.Position[x] == 'WR':
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'recRec', 'recYds', 'recAvg', 'recTD', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             pd.merge(df_player, college_stats)
        
#         elif df.Position[x] == 'TE':
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'recRec', 'recYds', 'recAvg', 'recTD', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             pd.merge(df_player, college_stats)
        
#         elif df.Position[x] == 'K':
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts', 'Punts', 'puntYds', 'puntAvg']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             pd.merge(df_player, college_stats)
        
#         elif df.Position[x] == 'P':
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'Punts', 'puntYds', 'puntAvg', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             pd.merge(df_player, college_stats)
    
#         else:
#             df_player = pd.read_html(full_url, skiprows=0)[0]
#             df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'tackleSolo', 'tackleAst', 'tackleTot', 'tackleLoss', 'Sk', 'defInt', 'defYds', 'defAvg', 'defIntTD', 'defIntPD', 'fumFR', 'fumYds', 'fumTD', 'fumFF']
#             df_player = df_player[df_player.Player == 'Career']
#             df_player = df_player.reset_index(drop=True)
#             df_player.iloc[0,0] = df.Player[x]
#             df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
#             pd.merge(df_player, college_stats)
#         x = x + 1
#     except:
#         print('Bagel, Dave?')

        
# college_stats

In [12]:
pre_url = "https://www.sports-reference.com/cfb/players/"
post_url = "-1.html"
x = 0
first = df.First[x].lower()
last = df.Last[x].lower()

In [13]:
full_url = f'{pre_url}{first}-{last}{post_url}'

In [14]:
df_player = pd.read_html(full_url, skiprows=0)[0]
df_player

  Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Year                School               Conf
0              *2005  North Carolina State                ACC
1             Career  North Carolina State                NaN

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Tackles          \
               Class                Pos                  G    Solo Ast Tot
0                 JR                 DL               12.0      32  30  62
1                NaN                NaN                NaN      32  30  62

              Def Int                 Fumbles
   Loss    Sk     Int Yds Avg  TD  PD      FR Yds  TD  FF
0  24.0  14.5     NaN NaN NaN NaN NaN     NaN NaN NaN NaN
1  24.0  14.5     NaN NaN NaN NaN NaN     NaN NaN NaN NaN

In [15]:
# RB Position

# df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'recRec', 'recYds', 'recAvg', 'recTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
# df_player = df_player[df_player.Player == 'Career']
# df_player = df_player.reset_index(drop=True)
# df_player.iloc[0,0] = df.Player[x]
# df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)


# college_stats = pd.merge(college_stats, df_player, how='left', on=['Player', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'recRec', 'recYds', 'recAvg', 'recTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD'])
# college_stats

In [16]:
# Defensive Positions

df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'tackleSolo', 'tackleAst', 'tackleTot', 'tackleLoss', 'Sk', 'defInt', 'defYds', 'defAvg', 'defIntTD', 'defIntPD', 'fumFR', 'fumYds', 'fumTD', 'fumFF']
df_player = df_player[df_player.Player == 'Career']
df_player = df_player.reset_index(drop=True)
df_player.iloc[0,0] = df.Player[x]
df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
# df_player = df_player.set_index(df_player.Player)
# df_player = df_player.rename(columns={'Player': 'Name'})
college_stats = pd.merge_ordered(college_stats, df_player, left_on=['Player', 'tackleSolo', 'tackleAst', 'tackleTot', 'tackleLoss', 'Sk', 'defInt', 'defYds', 'defAvg', 'defIntTD', 'defIntPD', 'fumFR', 'fumYds', 'fumTD', 'fumFF'], right_on=['Player', 'tackleSolo', 'tackleAst', 'tackleTot', 'tackleLoss', 'Sk', 'defInt', 'defYds', 'defAvg', 'defIntTD', 'defIntPD', 'fumFR', 'fumYds', 'fumTD', 'fumFF'], how='right')
college_stats

,Player,passCmp,passAtt,passPct,passYds,passY/A,passAY/A,passTD,passInt,passRate,...,Sk,defInt,defYds,defAvg,defIntTD,defIntPD,fumFR,fumYds,fumTD,fumFF
0,Mario Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# college_stats.to_csv('Check.csv')

In [18]:
#df_player = df_player

In [19]:
# QB Position

# df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'passCmp', 'passAtt', 'passPct', 'passYds', 'passY/A', 'passAY/A', 'passTD', 'passInt', 'passRate']
# df_player = df_player[df_player.Player == 'Career']
# df_player = df_player.reset_index(drop=True)
# df_player.iloc[0,0] = df.Player[x]
# df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
# college_stats = pd.merge(college_stats, df_player, how='left', on=['Player', 'passCmp', 'passAtt', 'passPct', 'passYds', 'passY/A', 'passAY/A', 'passTD', 'passInt', 'passRate'])
# college_stats

In [20]:
# WR & TE Positions

# df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'recRec', 'recYds', 'recAvg', 'recTD', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
# df_player = df_player[df_player.Player == 'Career']
# df_player = df_player.reset_index(drop=True)
# df_player.iloc[0,0] = df.Player[x]
# df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)

In [21]:
# K Position

# df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts', 'Punts', 'puntYds', 'puntAvg']
# df_player = df_player[df_player.Player == 'Career']
# df_player = df_player.reset_index(drop=True)
# df_player.iloc[0,0] = df.Player[x]
# df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)

In [22]:
# P Position

# df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'Punts', 'puntYds', 'puntAvg', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts']
# df_player = df_player[df_player.Player == 'Career']
# df_player = df_player.reset_index(drop=True)
# df_player.iloc[0,0] = df.Player[x]
# df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)